### ISSUE TITLE
Use $HOME enviromnent variable when writing default configuration

### ISSUE THREAD

**Issue by planglois** [Norival/BibTuX#1]
Yo!

I just noticed you've hard coded the default configuration file path to "/home/xavier/...". Use the $HOME variable instead: http://www.cplusplus.com/reference/cstdlib/getenv/.

Biz

**Comment by norival** [comment]
Ah! Thank you, I didn't know how to do that when I coded this part so I made it simple. I'm fixing it ;)

**Comment by norival** [comment]
It's fixed :) Thank you for the advice!
